<InfoScreen>:
    canvas:
        Color:
            rgba: 14,51,244,0.1
        Rectangle:
            pos: self.pos
            size: self.size
    Label:
        text: "Info"
        font_name: "Fonts/Orbitron-Bold.ttf"
        font_size: 100
        size_hint: .6, .1
        pos_hint: {'x':.2, 'y':.8}
        color: 0,0,255,0.2

    TextInput:
        multiline: False
        size_hint: .6, .1
        pos_hint: {'x':.09, 'y':.5}
        font_size: 23
        background_color: 14,51,244,0
